FROM nvidia/cuda:12.4.0-base-ubuntu22.04

# Minimal setup
RUN apt-get update \
 && apt-get install -y locales lsb-release
ARG DEBIAN_FRONTEND=noninteractive
RUN locale-gen en_US en_US.UTF-8 && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8
SHELL [ "/bin/bash" , "-c" ]

# Install ROS2 Humble
RUN apt update \
 && apt install -y --no-install-recommends curl \
 && apt install -y --no-install-recommends gnupg2 \
 && rm -rf /var/lib/apt/lists/*
 
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

RUN apt update \
 && apt install -y ros-humble-desktop \
 && apt install -y ros-humble-ros-gz

RUN apt-get install -y python3-rosdep \
 && apt-get install -y python3-colcon-common-extensions

RUN apt-get install -y git

RUN apt update

RUN apt-get install -y ros-humble-ros2-control \
    ros-humble-ign-ros2-control \
    ros-humble-joint-state-broadcaster \
    ros-humble-joint-state-publisher \
    ros-humble-joint-trajectory-controller \
    ros-humble-velocity-controllers \
    ros-humble-pointcloud-to-laserscan \
    ros-humble-rmw-cyclonedds-cpp \
    ros-humble-plotjuggler-ros \
    ros-humble-rqt-robot-steering

RUN apt-get install -y net-tools \
    && apt-get install -y gedit

RUN mkdir -p /tecdron_ws/src \
    && source /opt/ros/humble/setup.bash     

COPY ./ /tecdron_ws/src 

WORKDIR /tecdron_ws

RUN source /opt/ros/humble/setup.bash  \
    && colcon build \
    && source install/setup.bash

# Set environment variables
#ENV ROS_DOMAIN_ID=1
#ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp


# Define entrypoint
CMD ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && colcon build && source install/setup.bash && ros2 launch robot_gazebo main_robot.launch.py"]




