FROM nvidia/cuda:12.4.0-base-ubuntu22.04

# Minimal setup
RUN apt-get update \
 && apt-get install -y locales lsb-release
ARG DEBIAN_FRONTEND=noninteractive
RUN locale-gen en_US en_US.UTF-8 && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG en_US.UTF-8

# Install ROS2 Humble
RUN apt update \
 && apt install -y --no-install-recommends curl \
 && apt install -y --no-install-recommends gnupg2
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

RUN apt update \
# && apt upgrade \
 && apt install -y ros-humble-desktop \
 && apt install -y ros-humble-gazebo-ros-pkgs

#RUN pip install --upgrade pip==24.0
RUN apt-get install -y git=2.34.1

RUN mkdir /tecdron_ws/src
WORKDIR /tecdron_ws

# colocar aqui o git clone desse meu projeto
RUN cd src && git clone 

# Install dependencies
RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions \
    python3-vcstool \
    && rosdep update \
    && rosdep install --from-paths src --ignore-src -r -y


RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc