FROM nvidia_ros_humble:latest

SHELL [ "/bin/bash" , "-c" ]

# Install catkin tools#
RUN apt-get update \
    && apt-get install -y git python3-colcon-common-extensions \
    && apt-get install -y \
        ros-humble-xacro \
        ros-humble-urdf \
        ros-humble-ros2-control \
        ros-humble-gazebo-ros2-control \
        ros-humble-joint-state-publisher \
        ros-humble-joint-trajectory-controller \
        ros-humble-joint-state-broadcaster \
        ros-humble-velocity-controllers \
        ros-humble-pcl-ros 

RUN apt-get install net-tools


RUN mkdir -p /tecdron_ws/src \
    && source /opt/ros/humble/setup.bash 
    
COPY ./ /tecdron_ws/src 

WORKDIR /tecdron_ws
RUN source /opt/ros/humble/setup.bash \
    && colcon build \
    && source /tecdron_ws/install/setup.bash

RUN echo "source /tecdron_ws/install/setup.bash" >> ~/.bashrc

